#!/usr/bin/env bash
# Regenerate ansible/roles/bench/files/python-constraints.txt from the bench in
# the test container, after a green `tests/gate.sh`: that build's Python
# packages become the ones every later build installs.
#
#   tests/gate.sh && scripts/freeze-python-deps.sh && tests/gate.sh
#
# Run it after moving frappe_commit, whose new requirements the old
# constraints may not satisfy (bench init then fails with a resolver error).
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=ansible/roles/bench/files/python-constraints.txt
{
  cat <<'HEADER'
# Every Python package in the bench's env, at the version the last green build
# installed. The bench role passes this file to `bench init` (UV_CONSTRAINT /
# PIP_CONSTRAINT), so a build weeks later installs exactly the same set instead
# of whatever Frappe's `~=` ranges resolve to that day. The verify role checks
# it. Frappe's git dependencies (gunicorn, pypika) aren't listed: its
# pyproject.toml already pins them by commit.
#
# Generated by scripts/freeze-python-deps.sh; don't edit by hand.
HEADER
  podman exec -u vagrant -w /home/vagrant/frappe-bench -e PATH=/usr/local/bin:/usr/bin:/bin frappe-dev-test \
    uv pip freeze --exclude-editable --python env/bin/python 2>/dev/null \
    | grep -E '^[A-Za-z0-9_.-]+==' | sort -f
} > "$OUT"
echo "wrote $OUT ($(grep -c '==' "$OUT") packages)"
